name: CI

on:
  push:
    branches: [ test ]

jobs:
  in-docker_test:
    name: Testes automatizados
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Run Tests
        run: mvn -B test



